// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pharmaos-variants/DarkEmerald.tsx": () => import("../components/mockups/pharmaos-variants/DarkEmerald.tsx"),
  "./components/mockups/pharmaos-variants/GlassLuxury.tsx": () => import("../components/mockups/pharmaos-variants/GlassLuxury.tsx"),
  "./components/mockups/pharmaos-variants/NeonCyberpunk.tsx": () => import("../components/mockups/pharmaos-variants/NeonCyberpunk.tsx")
};
